#common
agent: 'alm'
device: 'cuda'
seed: -1

#benchmark
benchmark: 'dmc'
id: 'walker-walk'
action_repeat: 2

#data 
num_train_steps: 500000 # 1M if action_repeat=2
explore_steps: 5000 # 10 episode if action_repeat=2
max_episode_steps: 1000
env_buffer_size: 1000000
batch_size: 512
seq_len: 3

#learning
gamma: 0.99
tau: 0.005
target_update_interval: 1
lambda_cost: 0.1
lr: {'model' : 0.0001, 'reward' : 0.0001, 'critic' : 0.0001, 'actor' : 0.0001}
max_grad_norm: 100.0
update_every_steps: 2

#exploration
expl_start: 1.0
expl_end: 0.1
expl_duration: 200 # episodes
stddev_clip: 0.3

#hidden_dims and layers
latent_dims: 50
hidden_dims: 512
model_hidden_dims: 1024

#bias evaluation
eval_bias: False 
eval_bias_interval: 500

#evaluation
eval_episode_interval: 25
num_eval_episodes: 10

#logging
wandb_log: true
wandb_run_name: 'ALM'
log_interval: 500

#saving
save_snapshot: False
save_snapshot_interval: 50000

# hydra:
#   run:
#     dir: ./local_exp/alm/${id}_${seed}
#   job:
#     chdir: True

run_suffix: 0
# ref: https://stackoverflow.com/questions/65104134/disable-file-output-of-hydra
hydra:  
    output_subdir: null  
    run:  
        dir: .
